config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    sign_up: ''
  }
  

  root 'home#index'

  post 'send_mail' => "home#send_mail", as: :send_mail
  
  get 'fetch_emails' => "home#fetch_emails", as: :fetch_emails
  
  get 'download_data' => "home#download_data", as: :download_data
  
  post 'import_data' => "home#import_data", as: :import_data
  
  get 'business_urls' => "home#business_urls", as: :business_urls
  
  get 'send_enquiries' => "home#send_enquiries", as: :send_enquiries
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	  @business_enquiries = BusinessEnquiry.all
	end
	
  # Sends business enquiry to provided url.
	def send_mail
	  status = BusinessEnquiry.send_enquiry(params[:business_url])
	  if status == "success"
	   BusinessUrl.create(url: params[:business_url], enquiry_sent: true)
	   redirect_to '/', notice: "Business enquiry sent."
	  else
	    redirect_to '/', alert: "Could not find Email link on this webpage. Enquiry sending failed."
    end
	end
	
	# to send multiple business enquiries, sends enquiries to all urls where enquiry_sent is false.
	def send_enquiries
    BusinessEnquiry.send_business_enquiry
	  redirect_to business_urls_path, notice: "Business enquiries sent to the urls where email address was present."
	end
	
	# Fetch to-emails from gmail received emails from yp.com
	def fetch_emails
	 BusinessEnquiry.fetch_email(Constants::GMAIL_USER, Constants::GMAIL_PASSWORD)
	 redirect_to '/', notice: "Emails fetched."
	end
	
	# Downloads business enquiry data in MS Excel file, only the records where emails ids are present.
	def download_data
	 file = BusinessEnquiry.download_enquiry_data
   send_data file, :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet", filename: "business_enquiries_#{Date.today}.xlsx"
	end
	
	# accepts uploaded csv file and imports business urls from csv file to database.
	def import_data
	 BusinessEnquiry.import(params[:file])
	 redirect_to business_urls_path, notice: "Business urls imported."
	end
	
	# Business urls page, where urls are separately shown sent/to-be-sent.
	def business_urls
	 @unsent_urls = BusinessUrl.where(enquiry_sent: false)
	 @sent_urls = BusinessUrl.where(enquiry_sent: true)
	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/business_urls.html.erb
<% if @unsent_urls.count > 0 %>
  <%= link_to "Send Business Enquiries", send_enquiries_path, :id => "link_to_send", :class => "btn btn-default btn-warning pull-right", :"data-trigger" => "hover", :"data-placement" => "left", :"data-content" => "Sends enquiries to all the urls from the below table. The enquiries will be sent in batch of 20 urls in one go.", :rel => "popover", :onClick => 'javascript:$("#link_to_send").hide();$("#sending").show();' %>
<% else %>
  <%= link_to "No URLs", "#", :class => "btn btn-default btn-warning pull-right", :"data-trigger" => "hover", :"data-placement" => "left", :"data-content" => "Currently there are no unsent urls in the system to send the enquiries. Import urls first.", :rel => "popover" %>
<% end %>

<%= link_to "Sending...", "#", :id => "sending", :class => "btn btn-default btn-warning pull-right", :disabled => "disabled", :style => "display:none;" %>

<h4>Import Business Urls</h4>
<%= form_tag import_data_path, multipart: true do %>
  <div class="row">
    <%= file_field_tag :file, required: true, :class => "col-md-3", :style => "padding-top:7px;" %>
    <%= submit_tag "import", :class => "btn btn-default btn-info" %>
  </div>
<% end -%>
<br/>
<%= link_to "Download sample csv", root_path << "business_enquiries.csv" %>
<br/><br/>

<div>
  
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#to_be_sent" aria-controls="to_be_sent" role="tab" data-toggle="tab">Enquiries to be sent <span class="badge"><%= @unsent_urls.count %></span></a></li>
    <li role="presentation"><a href="#sent" aria-controls="sent" role="tab" data-toggle="tab">Enquiries sent <span class="badge"><%= @sent_urls.count %></span></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="to_be_sent">
      <table class="table table-hover">
        <tr>
          <th style="border:none;">URLs</th>
        </tr>
        <% @unsent_urls.each do |url| %>
        <tr>
          <td><%= link_to url.url, url.url, target: "_blank" %></td>
        </tr>
        <% end %>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane" id="sent">
      <table class="table table-hover">
        <tr>
          <th style="border:none;">URLs</th>
        </tr>
        <% @sent_urls.each do |url| %>
        <tr>
          <td><%= link_to url.url, url.url, target: "_blank" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<%= link_to "Send Business Enquiry", "#", :class => "btn btn-default btn-info", :id => "editPostBtn", :onClick => "openBusinessEnquiryModal();" %>

<%= link_to "Fetch Business Emails", fetch_emails_path, :id => "link_to_fetch", :class => "btn btn-default btn-warning", :"data-trigger" => "hover", :"data-content" => "This will fetch the emails for those businesses where emails are not present (marked in blue below).", :rel => "popover", :onClick => 'javascript:$("#link_to_fetch").hide();$("#fetching").show();' %>

<%= link_to "Fetching...", "#", :id => "fetching", :class => "btn btn-default btn-warning", :disabled => "disabled", :style => "display:none;" %>

<%= link_to "Download Business Data", download_data_path, :class => "btn btn-default btn-warning pull-right", :"data-trigger" => "hover", :"data-placement" => "left", :"data-content" => "Downloads MS Excel file.", :rel => "popover" %>

<%= render partial: "modals/business_enquiry_modal" %>

<br/><br/>
<h4>Business enquiries</h4>

<table class="table table-hover">
  <tr>
    <th>Email</th>
    <th>Business name</th>
    <th>Business address</th>
  </tr>
  <% @business_enquiries.each do |enq| %>
  <tr class="<%= ("info" unless enq.has_email_address) %>">
    <td><%= enq.email_address %></td>
    <td><%= enq.business_name %></td>
    <td><%= enq.business_address %></td>
  </tr>
  <% end %>
</table>